version: "3.8"

services:
  mongodb:
    image: mongo:7.0
    container_name: todo_mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: todoapp
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - app-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh admin --quiet --username admin --password password123
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: todo_app
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - MONGODB_URI=mongodb://admin:password123@mongodb:27017/todoapp?authSource=admin
      - PORT=5000
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - app-network

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge
